CREATE TABLE Companies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    inn VARCHAR(12) UNIQUE NOT NULL,
    type VARCHAR(255) NOT NULL,
    short_description TEXT,
    full_description TEXT,
    products TEXT,
    services TEXT,
    video_url VARCHAR(255),
    logo_url VARCHAR(255),
    image1_url VARCHAR(255),
    image2_url VARCHAR(255),
    image3_url VARCHAR(255),
    image4_url VARCHAR(255),
    region VARCHAR(100),
    address VARCHAR(255),
    phone VARCHAR(20),
    telegram VARCHAR(255),
    vk VARCHAR(255),
    whatsapp VARCHAR(20),
    viber VARCHAR(20),
    website_url VARCHAR(255)
);